[package]
name = "value-enum"
version = "1.0.0"
edition = "2021"
description = "Macro for generating enums associated with values"
authors = ["Mira Nekomimi-Sireneva <nekomimimira@gmail.com>"]
license = "MIT"
repository = "https://github.com/mira-neko/value-enum"

[dependencies]
