[package]
name = "value-enum"
version = "0.6.0"
edition = "2021"
description = "Macro for generating enums associated with values"
authors = ["Мира Лущаева <miralushch@gmail.com>"]
license = "MIT"
repository = "https://github.com/miralushch/value-enum"

[dependencies]
