[package]
name = "value-enum"
version = "0.5.0"
edition = "2021"
description = "Macro for generating enums associated with values"
authors = ["Мира Лущаева <miralushch@gmail.com>"]
license = "MIT"

[dependencies]
